import type { Metadata } from "next";

import "@/styles/globals.scss";
import Providers from "@/providers";
import { ReactElement } from "react";
import MainTemplate from "@/template";
import { AOSInit } from "@/aos";
import MovingEllipseBackground from "@/components/Backgrounds/EllipseBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactElement;
}>) {
  return (
    <html lang="en">
      <AOSInit />
      <body
        className={`relative min-h-dvh bg-background font-sans antialiased `}
      >
        <aside className={`fixed -right-10 -top-10 z-[-1] opacity-90`}>
          <MovingEllipseBackground />
        </aside>

        <Providers>
          <MainTemplate>{children}</MainTemplate>
        </Providers>
      </body>
    </html>
  );
}
